#!/usr/bin/env bash
set -euo pipefail

# docker-entrypoint.sh
# Generates /app/config.py from environment variables if not mounted/provided

if [ ! -f /app/config.py ]; then
    if [ -z "${TOKEN:-}" ]; then
        echo "ERROR: TOKEN environment variable is required if config.py is not provided" >&2
        exit 1
    fi

    echo "Generating /app/config.py from environment variables..."
    cat > /app/config.py <<-EOF
    # generated by docker-entrypoint.sh
    TOKEN = "${TOKEN}"
EOF

    # Optionally add CHAT_ID if provided
    if [ -n "${CHAT_ID:-}" ]; then
        echo "CHAT_ID = \"${CHAT_ID}\"" >> /app/config.py
    fi
fi

# Exec the container CMD
exec "$@"